apiVersion: apps/v1
kind: Deployment
metadata:
name: sam-resnet
spec:
  selector:
    matchLabels:
      app: sam-resnet
  replicas: 2 
  template:
    metadata:
      labels:
        app: sam-resnet
    spec:
      containers:
       - name: sam-resnet
         image: samkalgudi24/vehicleclassification:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
name: sam-resnet
labels:
  app: sam-resnet
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: sam-resnet
type: LoadBalancer